baseline: B3
seed: 42
num_classes: 9

experiment:
  name: "Baseline_B3"
  description: "ResNet50 baseline for single-frame person action recognition with player crops"
  version: 1


data:
  annot_file: data_set/annot_all.pkl
  videos_dir: data_set
  splits:
    train: [7, 10]
    val: [10]
    test: [7]

labels:
  class_names:
    - Waiting
    - Setting
    - Digging
    - Falling
    - Spiking
    - Blocking
    - Jumping
    - Moving
    - Standing

training:
  epochs: 3
  batch_size: 2
  lr: 0.0001
  optimizer: AdamW
  weight_decay: 0.0001
  num_workers: 0
  mixup: True
  scheduler: "StepLR"

output:
  base_dir: outputs/B1
  checkpoints_dir: outputs/B1/checkpoints
  results_dir: outputs/B1/results
  mlruns_dir: outputs/B1/mlruns
